@extends('layouts.owner.app')
@section('content')
@include('layouts.owner.sidebar')
  <section class="main-content">
    <div class="topbar">
      
      <div class="welcome-text"><strong>Welcome, Owner!</strong></div>

      <!-- Actions: Notification Icon and Logout Button (right-aligned) -->
      <div class="topbar-actions">
        <!-- Notification Icon -->
        <button type="button" class="icon-btn" aria-label="Notifications">
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none"
               stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M15 17H9a4 4 0 0 1-4-4V9a7 7 0 1 1 14 0v4a4 4 0 0 1-4 4z"/>
            <path d="M10 21a2 2 0 0 0 4 0"/>
          </svg>
          <span class="badge">2</span> {{-- Notification count --}}
        </button>

        <!-- Logout Button -->
        <form method="POST" action="{{ route('logout') }}">
          @csrf
          <button type="submit" class="logout-btn">
            Logout
          </button>
        </form>
      </div>
    </div>

    <!-- Table container for reports -->
    <div class="table-container">
      <h3>Reports</h3>
      <table>
        <thead>
          <tr>
            <th>Report Name</th>
            <th>Description</th>
            <th>Generated By</th>
            <th>Date Generated</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Sales Report</td>
            <td>A comprehensive overview of sales over the last month.</td>
            <td>Owner</td>
            <td>2025-08-30</td>
            <td>
              <button class="btn-view">View</button>
              <button class="btn-download">Download</button>
            </td>
          </tr>
          <tr>
            <td>Inventory Report</td>
            <td>Current stock levels for all products in the inventory.</td>
            <td>Manager</td>
            <td>2025-08-29</td>
            <td>
              <button class="btn-view">View</button>
              <button class="btn-download">Download</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
@endsection
