@extends('layouts.owner.app')
@section('content')
@include('layouts.owner.sidebar')

  <section class="main-content">

    <!-- Table container for reports -->
    <div class="table-container">
      <h3>Reports</h3>
      <table>
        <thead>
          <tr>
            <th>Report Name</th>
            <th>Description</th>
            <th>Generated By</th>
            <th>Date Generated</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Sales Report</td>
            <td>A comprehensive overview of sales over the last month.</td>
            <td>Owner</td>
            <td>2025-08-30</td>
            <td>
              <button class="btn-view">View</button>
              <button class="btn-download">Download</button>
            </td>
          </tr>
          <tr>
            <td>Inventory Report</td>
            <td>Current stock levels for all products in the inventory.</td>
            <td>Manager</td>
            <td>2025-08-29</td>
            <td>
              <button class="btn-view">View</button>
              <button class="btn-download">Download</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
@endsection
