<?php

return [
	'aliases' => [
		'classic-save-the-date' => 'default',
	],
	'default' => [
		'name' => 'Classic Save The Date',
		'description' => 'Minimal typographic save-the-date layout with editable backgrounds.',
		'front_svg' => resource_path('templates/default/front.svg'),
		'back_svg' => resource_path('templates/default/back.svg'),
	'preview_image' => 'images/templates/default-preview.png',
		'text_fields' => [
			[
				'node' => 'front-date',
				'placeholder' => '06.28.26',
				'default' => '',
				'side' => 'front',
				'top' => 18,
				'left' => 50,
				'align' => 'center',
				'font_size' => 28,
			],
			[
				'node' => 'front-save',
				'placeholder' => 'SAVE',
				'default' => '',
				'side' => 'front',
				'top' => 28,
				'left' => 50,
				'align' => 'center',
				'font_size' => 32,
				'letter_spacing' => 0.35,
			],
			[
				'node' => 'front-dateword',
				'placeholder' => 'DATE',
				'default' => '',
				'side' => 'front',
				'top' => 36,
				'left' => 50,
				'align' => 'center',
				'font_size' => 16,
				'letter_spacing' => 0.5,
			],
			[
				'node' => 'front-names',
				'placeholder' => 'KENDRA AND ANDREW',
				'default' => '',
				'side' => 'front',
				'top' => 48,
				'left' => 50,
				'align' => 'center',
				'font_size' => 22,
			],
			[
				'node' => 'front-location',
				'placeholder' => 'BROOKLYN, NY',
				'default' => '',
				'side' => 'front',
				'top' => 58,
				'left' => 50,
				'align' => 'center',
				'font_size' => 16,
				'letter_spacing' => 0.1,
			],
			[
				'node' => 'back-heading',
				'placeholder' => 'RECEPTION DETAILS',
				'default' => '',
				'side' => 'back',
				'top' => 26,
				'left' => 50,
				'align' => 'center',
				'font_size' => 26,
			],
			[
				'node' => 'back-body',
				'placeholder' => "Join us for dinner at seven o'clock in the evening.\nThe Foundry, Long Island City.",
				'default' => '',
				'side' => 'back',
				'top' => 43,
				'left' => 50,
				'align' => 'center',
				'font_size' => 16,
				'letter_spacing' => 0.05,
			],
		],
		'image_slots' => [
			[
				'side' => 'front',
				'node' => 'front-background',
				'default' => 'images/templates/default-front.jpg',
			],
			[
				'side' => 'back',
				'node' => 'back-background',
				'default' => 'images/templates/default-back.jpg',
			],
		],
	],
];
